# Numbers Part 2

## Margins

In [1]:
import numpy as np

In [2]:
np.random.seed(123)
x = np.random.randint(0, 10, (3,5))

In [3]:
x

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3]])

In [4]:
x.sum(axis=0) #want column sum, get rid of the rows and vice versa

array([20,  8,  7, 10,  7])

In [5]:
x.sum(axis=1)

array([14, 17, 21])

## Broadcasting

In [6]:
x.shape

(3, 5)

### Scale columns to have zero mean and unit standard deviation

In [7]:
cm = x.mean(axis=0) #wipe out rows to get column mean
cs = x.std(axis=0)

In [11]:
cm

array([6.66666667, 2.66666667, 2.33333333, 3.33333333, 2.33333333])

In [8]:
cm.shape, cs.shape

((5,), (5,))

In [9]:
cx = (x - cm)/cs

In [10]:
cx

array([[-1.41421356, -0.26726124,  1.3970014 , -0.57932412,  0.70710678],
       [ 0.70710678,  1.33630621, -0.50800051, -0.82760589, -1.41421356],
       [ 0.70710678, -1.06904497, -0.88900089,  1.40693001,  0.70710678]])

In [ ]:
cx.mean(axis=0)

In [ ]:
cx.std(axis=0)

### Scale rows to have zero mean and unit standard deviation

In [12]:
rm = x.mean(axis=1)
rs = x.std(axis=1)

In [17]:
rm.shape, rs.shape

((3,), (3,))

In [18]:
rm

array([2.8, 3.4, 4.2])

In [19]:
rm[:,np.newaxis]

array([[2.8],
       [3.4],
       [4.2]])

In [14]:
rx = (x - rm[:, np.newaxis])/rs[:, np.newaxis] #need to change it to column, and then broadcat. either use reshape or this. Use np.newaxis for more readability


In [15]:
rx

array([[-0.46499055, -0.46499055,  1.85996222, -1.04622875,  0.11624764],
       [ 1.60065346,  0.74316054, -0.68599434, -0.97182532, -0.68599434],
       [ 1.17953565, -1.03209369, -1.03209369,  1.17953565, -0.29488391]])

In [16]:
rx = (x - rm/rs)

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [ ]:
rx

In [ ]:
rx.mean(axis=1)

In [ ]:
rx.std(axis=1)

## Making copies

In [20]:
x = np.arange(1, 7).reshape((2,3))

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.tile(x, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [23]:
np.repeat(x, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [24]:
np.repeat(x, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [25]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [26]:
a = np.arange(1,5).reshape((2,2)).astype('int')
b = np.ones((2,2)).astype('int')

In [27]:
a

array([[1, 2],
       [3, 4]])

In [28]:
b

array([[1, 1],
       [1, 1]])

In [29]:
np.kron(a, b) #

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

## Merge

In [30]:
x1 = np.ones((2,3), dtype='int')
x2 = 2*np.ones((2,4), dtype='int')
x3 = 3*np.ones((4,3), dtype='int')

In [31]:
x1

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
x2

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [33]:
x3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### Merging columns

In [34]:
np.hstack([x1, x2])

array([[1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 2]])

In [35]:
np.c_[x1, x2]

array([[1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 2]])

In [36]:
np.concatenate([x1, x2], axis=1)

array([[1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 2]])

### Merging rows

In [37]:
np.vstack([x1, x3]) #dstack - put a matrix behind it in the 3rd dimension

array([[1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [38]:
np.r_[x1, x3]

array([[1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [39]:
np.concatenate([x1, x3], axis=0) #under the hood what the above 2 are using

array([[1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

## Split

In [40]:
x = np.kron(a, b)
x

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [4]:
import numpy as np
print(np.kron.__doc__)


    Kronecker product of two arrays.

    Computes the Kronecker product, a composite array made of blocks of the
    second array scaled by the first.

    Parameters
    ----------
    a, b : array_like

    Returns
    -------
    out : ndarray

    See Also
    --------
    outer : The outer product

    Notes
    -----
    The function assumes that the number of dimensions of `a` and `b`
    are the same, if necessary prepending the smallest with ones.
    If `a.shape = (r0,r1,..,rN)` and `b.shape = (s0,s1,...,sN)`,
    the Kronecker product has shape `(r0*s0, r1*s1, ..., rN*SN)`.
    The elements are products of elements from `a` and `b`, organized
    explicitly by::

        kron(a,b)[k0,k1,...,kN] = a[i0,i1,...,iN] * b[j0,j1,...,jN]

    where::

        kt = it * st + jt,  t = 0,...,N

    In the common 2-D case (N=1), the block structure can be visualized::

        [[ a[0,0]*b,   a[0,1]*b,  ... , a[0,-1]*b  ],
         [  ...                              ...   ],
         

In [41]:
for block in np.split(x, 2):
    print(block)

[[1 1 2 2]
 [1 1 2 2]]
[[3 3 4 4]
 [3 3 4 4]]


In [42]:
for block in np.split(x, 2, axis=0):
    print(block)

[[1 1 2 2]
 [1 1 2 2]]
[[3 3 4 4]
 [3 3 4 4]]


In [43]:
for block in np.split(x, 2, axis=1):
    print(block)

[[1 1]
 [1 1]
 [3 3]
 [3 3]]
[[2 2]
 [2 2]
 [4 4]
 [4 4]]


In [ ]:
#ufuncs - simplest ufuncs are operators. + is same as an add function
#all numpy functions are designed to work on array - vectorized functions ufuncs. 
#instead of using for loops, always try using universal functions or operators instead


In [44]:
#matrix multiplication
xs=np.arange(3).reshape((-1,1))
ys=np.array([4,5,6]).reshape((-1,1))
np.dot(xs.T,ys)
xs.T @ ys


array([[17]])